openapi: 3.0.0
info:
  title: Hotel America API
  contact:
    email: gerardodev25@gmail.com
  license:
    name: MIT License
  version: 1.0.0
  description: this the api documentation for hotel america where you can find all the endpoints and how to use them

servers:
  - url: http://localhost:3000
    description: Local server

# paths:
#   $ref: './users.yaml'
#   $ref: './products.yaml'
